### ISSUE TITLE
Prepare presentation materials - ppt

### ISSUE THREAD

**Issue by Jaykay2020** [subiready/SQL-#10]
Close the issue when PPT is finalized

**Comment by Jaykay2020** [comment]
label을 활용한 issue 관리

![issueList_closed](https://user-images.githubusercontent.com/63007709/87518261-03040300-c6bb-11ea-94be-063d0551a6d1.jpg)

**Comment by Jaykay2020** [comment]
milestones을 사용하여 프로젝트 진척 관리

![milestones](https://user-images.githubusercontent.com/63007709/87518295-0bf4d480-c6bb-11ea-80b4-04ef45ea1565.jpg)

**Comment by pure-teatree** [comment]
[깃 과정(스크린샷).zip](https://github.com/subiready/SQL-/files/4923687/default.zip)

로컬저장소에서 프로젝트한 과정 스크릿샷입니다. 😃

**Comment by Jaykay2020** [comment]
kanban을 통한 to-do 관리

![projectKanban](https://user-images.githubusercontent.com/63007709/87519068-11065380-c6bc-11ea-8adb-496ea7cb7a3f.jpg)

**Comment by SooYangKim** [comment]
![라벨종류](https://user-images.githubusercontent.com/68219038/87521107-de118f00-c6be-11ea-8f47-a218f61e0a07.gif)
![활용](https://user-images.githubusercontent.com/68219038/87521112-df42bc00-c6be-11ea-93b0-fbbeb03be376.gif)

**Comment by pure-teatree** [comment]
위키 스크린샷 올립니다.
![wiki1 편집](https://user-images.githubusercontent.com/66557175/87521574-87f11b80-c6bf-11ea-8853-544752be0d11.PNG)
![wiki1](https://user-images.githubusercontent.com/66557175/87521585-8c1d3900-c6bf-11ea-9807-2a8bd7843534.PNG)
