### ISSUE TITLE
Finalize labels

### ISSUE THREAD

**Issue by Jaykay2020** [subiready/SQL-#9]
Provide screenshots in the comment and close the issue

**Comment by SooYangKim** [comment]
![라벨활용](https://user-images.githubusercontent.com/68219038/87519435-8f62f580-c6bc-11ea-9ac7-4d115acf0bd6.gif)
![라벨생성1](https://user-images.githubusercontent.com/68219038/87519445-91c54f80-c6bc-11ea-8034-4f2bce9cb152.gif)
![라벨활용1](https://user-images.githubusercontent.com/68219038/87519448-92f67c80-c6bc-11ea-9664-a9b03105056c.gif)

**Comment by SooYangKim** [comment]
![라벨종류](https://user-images.githubusercontent.com/68219038/87521066-cf2adc80-c6be-11ea-933e-e2ac236b2175.gif)
![활용](https://user-images.githubusercontent.com/68219038/87521070-d0f4a000-c6be-11ea-89a8-fc4e60ad0528.gif)
